# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'Utils1'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true
    preserveTimestamp: true
    
- task: AzureFileCopy@5
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/drop/*'
    AzureSubscription: 'Visual Studio Ultimate with MSDN (Bouvet)(ed952f43-e73c-4edb-8add-33484270d336)'
    Destination: 'AzureBlob'
    storage: 'kwitest2'
    ContainerName: 'AzurePipeLine'
    BlobPrefix: 'Utils1'

