# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'Utils1'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true
    preserveTimestamp: true
    delayBetweenRetries: 

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Appends to build file
      
      # Set timestamp and filename
      $timestamp = Get-Date -Format "HH:mm:ss dd.MM.yyyy"
      $filename = $(Build.ArtifactStagingDirectory) + "buildlog.txt"
      $msg = "Last updated:  " + $timestamp
      
      # Create file, ignore if exits, append info
      New-Item $filename -ErrorAction SilentlyContinue
      Add-Content $filename $msg

- task: AzureFileCopy@5
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/*'
    azureSubscription: 'KWIMunuTest - MSDN'
    Destination: 'AzureBlob'
    storage: 'kwitest2'
    ContainerName: 'AzurePipeLine'
    BlobPrefix: 'Utils1'

